config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'services', to: 'pages#services'
  get 'articles', to: 'pages#articles'
  get 'articles/new', to: 'pages#new'
  get 'articles/:id', to: 'pages#show', as: 'article'
  post 'articles', to: 'pages#create'
  get 'contacts', to: 'pages#contacts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :phone, :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def articles
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
   @post = Post.find(params[:id])
  end

  def create
    @post = @Post.new(post_params)
    @post.save
    redirect_to article_path(@post)
   end

  def contacts
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DraKg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

  <body>

   <%= render 'shared/navbar' %>

    <%= yield %>

  <%= render 'shared/footer' %>

    
  </body>
</html>

app/views/pages/_form.html.erb
<h1> CREATE NEW ARTICLE </h1>
<%= form_with(model: post, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class:'form-control', rows: 10 %>
  </div>
  
    <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Criando...' }%>
 
<% end %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/articles.html.erb
<h1>ALL POSTS </h1>

<ul>
  <% @posts.each do |post| %>
    <li><%= post.title %></li>
    <li><%= post.author %></li>
    <li><%= post.body %></li>
  <% end %>
</ul>


<%= link_to "CRIAR", articles_new_path, class:'btn btn-dark btn-lg' %>

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/index.html.erb
<h1>Home da Pagina</h1>
<p>Aqui vira todo conteudo da home da pagina</p>

app/views/pages/new.html.erb
<h1> CREATE NEW ARTICLE </h1>
<%= render 'form', post: @post %>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>

app/views/pages/show.html.erb
  <div class="shadow bg-light p-5 rounded">
    <div class="text-center mb-5">
      <h1><%= @post.title %></h1> 

      <p class="text-muted">
        <strong>Por <%= @post.author %></strong><br>
        <%= l @post.created_at, format: :long %>
      </p>
    </div>

      <div class="px-5">
        <%= @post.body.gsub("\n", "<br>").html_safe %>
      </div>

      <div class="text-center mt-5">
        <%= link_to "Voltar", articles_path, class:'btn btn-dark btn-lg' %>
      </div>   
  </div>

app/views/shared/_footer.html.erb
<div class="content">
    </div>
    <footer id="myFooter">
      <div class="footer-social">
        <a href="#" class="social-icons"><i class="fa fa-facebook"></i></a>
        <a href="#" class="social-icons"><i class="fa fa-instagram"></i></a>
        <a href="#" class="social-icons"><i class="fa fa-google"></i></a>
        <a href="#" class="social-icons"><i class="fa fa-whatsapp"></i></a>
        <p class="font-italic">© Todos os Direitos Reservados <%=Date.current.year%></p>
      </div>
    </footer>

app/views/shared/_navbar.html.erb
 <nav>
      <input type="checkbox" id="check">
      <label for="check" class="checkbtn">
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
      </label>
      <label class="logo">
        <%= link_to root_path do %>
          <%= image_tag('logo.png', class:'logo-kg', :alt => "LOGO-KG") %>
        <% end %>
      </label>
      <ul id="ul-nav">
        <li><%= link_to 'Início', root_path, class: 'link-nav ' %></li>
        <li><%= link_to 'Sobre Mim', about_path, class: 'link-nav' %></li>
        <li><%= link_to 'Procedimentos', services_path, class: 'link-nav' %></li>
        <li><%= link_to 'Artigos', articles_path, class: 'link-nav' %></li>
        <li><%= link_to 'Contato', contacts_path, class: 'link-nav' %></li>
      </ul>
    </nav>